### ISSUE TITLE
Addresses showing 0tz balance since Ithaca 2 upgrade

### ISSUE THREAD

**Issue by TofuTaco** [lousando/briskett#10]
Hi, first off I would like to thank you for this great project and for giving trezor compatibility with tezos. 

The issue is that addresses are showing 0tz balance since Ithaca 2 upgrade.

Sending out a transaction is still is working though, even though the balance says 0.

Thanks!

**Comment by lousando** [comment]
Thank you for reporting this. This issue has been patched in v0.17.3
