### ISSUE TITLE
Briskett not working anymore

### ISSUE THREAD

**Issue by clngr** [lousando/briskett#19]
Hapenning for some weeks now. Briskett now seems to have stopped working.

https://connect.trezor.io/ keeps on "loading" and nothing happens. Cache, etc., all cleaned/updated.

How to access the wallet with Trezor?

**Comment by lousando** [comment]
It seems that a new Trezor Bridge has been released, so Briskett will need to be updated for it to work again.

**Comment by clngr** [comment]
What can be done for it to work right now? Tried everything, running as an app, etc.

**Comment by clngr** [comment]
Trezor Bridge seems to be the same.

**Comment by lousando** [comment]
@clngr Not sure. I don't think Trezor firmware can be downgraded. Briskett sit will need to be updated.

I may have some time this weekend to patch it.

**Comment by clngr** [comment]
Firmware updated again from 2.6.0 to 2.6.3.

**Comment by lousando** [comment]
@clngr Briskett has been updated to use v9 of the TrezorConnect API. I've tested this to work with firmware 2.6.3 with a Trezor Model T. Please confirm that this issue is fixed for you.
