### ISSUE TITLE
Environment Variable Rename

### ISSUE THREAD

**Issue by lousando** [lousando/briskett#20]
`NUXT_ENV_TZSTATS_URL` is an old env var that needs to be renamed to `NUXT_ENV_TZPRO_URL`.
It's a lingering artifact of the old API that Briskett used to use.

**Comment by GajendraR** [comment]
i want to work on this issue

**Comment by lousando** [comment]
Woo, I appreciate it. Let me know if you have issues setting up your machine. I've recently updated the `README.md`

**Comment by lousando** [comment]
@GajendraR You'll have to pull down the repo on your local machine. The find every instance of `NUXT_ENV_TZSTATS_URL` URL and replace it.

You'll want to verify that you can successfully build the project using `yarn build`

**Comment by lousando** [comment]
Fixed in #21
