### ISSUE TITLE
Cannot see tokens using the Briskett app

### ISSUE THREAD

**Issue by DigitalDeejay** [lousando/briskett#24]
I can see my tokens at my wallet address using tzstats but balance shows as 0 using the Briskett app.

**Comment by lousando** [comment]
Interesting. I'll take a look immediately.

**Comment by lousando** [comment]
It seems I've hit the max API calls for TZ Stats for the month, so it's not returning any balance data anymore.

**Comment by DigitalDeejay** [comment]
Thank you!

**Comment by lousando** [comment]
@DigitalDeejay You should be able to see your balances again since it is the beginning of a new month, and my API key for TZ Stats has reset. I will implement a way to provide your own API key soon to mitigate this issue in the future.

**Comment by DigitalDeejay** [comment]
Thank you @lousando! Yes it is working again. Much appreciated.

**Comment by lousando** [comment]
@DigitalDeejay In version 0.22.0, I've introduced the ability to provide your TzPro API key. So, if the limit is ever hit, or if you want to add your own key, you can do so via the options menu I've introduced. Cheers 🍻

![Screenshot 2024-02-01 at 14 08 42](https://github.com/lousando/briskett/assets/1214300/20827808-de3f-4774-af73-018d339ce0ea)

![Screenshot 2024-02-01 at 14 08 55](https://github.com/lousando/briskett/assets/1214300/7d553a6e-5311-47e7-89be-2dad2c147ace)

**Comment by DigitalDeejay** [comment]
Fantastic addition! Thank you so much!
