### ISSUE TITLE
Emtpy balance and history

### ISSUE THREAD

**Issue by clngr** [lousando/briskett#25]
Got a "Connect v8 is deprecated. Please ask your DeFi platform/wallet developers (not Trezor) to update to Connect v9.", On Edge, Version 121.0.2277.83 (Official build) (64-bit).

Also, getting blank/empty history and balance on wallet. Transfers are failing. This happens also on Google Chrome, latest stable build 121.0.6167.86 64 bits.

TzStats API Status: OFFLINE

**Comment by lousando** [comment]
Yep, the empty balance is due to the #24 which is the API token getting rate limited.
It should be fixed by tomorrow, but I will add a feature that lets users add their own API tokens soon.

**Comment by lousando** [comment]
As for the issue with Edge I'll have to test that. Trezor Connect is already at v9, so it's likely something else.

**Comment by lousando** [comment]
I'm unable to replicate the issue for Microsoft Edge. If you're able to provide screenshots or a video I'm willing to look into this again.
