### ISSUE TITLE
Incorrect RPC endpoint for ECAD Labs

### ISSUE THREAD

**Issue by GImbrailo** [lousando/briskett#29]
Hi there

I work for ECAD Labs and noticed that the `ECAD Labs Node Status` is OFFLINE on https://briskett.app/. I also had a user of Briskett reach out to me regarding the RPC requests being blocked. We have moved off of the https://mainnet.api.tez.ie/ domain and are now using https://mainnet.ecadinfra.com/. I had a look through the code and I could not see where I could change this myself. Would it be possible for you to update the configuration for https://briskett.app/ to use the new RPC URL? This should get things working again. If there are any further issues or if you need specific RPCs, please feel free to reach out to me at ops@ecadlabs.com

**Comment by lousando** [comment]
Hey @GImbrailo thanks for the tip there. I've gone ahead and updated the RPC URL to `https://mainnet.ecadinfra.com/` now. It's set as an environment variable with the name of `PUBLIC_TAQUITO_RPC_URL`, so that's likely why you couldn't find it in the codebase.
