### ISSUE TITLE
Transaction Failure on Briskett

### ISSUE THREAD

**Issue by RobCombo** [lousando/briskett#30]
I tried to make a transaction on https://briskett.app/ but received the following failure message:

----Request to https://mainnet.ecadinfra.com/chains/main/blocks/head/helpers/forge/operations failed----

I used a Trezor Hardware wallett.

Thanks a lot in advance

**Comment by RobCombo** [comment]
May I ask if there is a possibility to fix this please?

**Comment by lousando** [comment]
@RobCombo This issue is now patched in v0.22.4

**Comment by prusnak** [comment]
@lousando Which commit did change the backend URL? All I can see are the changes in copy.

**Comment by lousando** [comment]
@prusnak `.env` change on the build side. A lot of Tezos RPCs are bow charging for access, so that's why Briskett broke. Had to spin up my own.
