### ISSUE TITLE
Wallet showing 0 tez

### ISSUE THREAD

**Issue by richardleaf** [lousando/briskett#32]
I logged in to my wallet today after a long period, and it is showing a balance of zero, which is a little concerning. 

Some troubleshooting steps I have already tried:
* I can confirm on tzkt that my balance is there, and I even sent 1 tez from a different account to the ledger/brisket account to see if that would do anything - the transaction showed successful on my Ledger devices and in tzkt. But the balance for my brisket account remained zero. 
* I have verified that the wallet addresses are correct (multiple times)
* I do not have a passphrase on this wallet, so it is not that I am adding a passphrase
* I created a new wallet using a passphrase, and sent it a small amount of tezos, which tzkt shows opened, and brisket also reports that account at a zero balance

What are my options at this point? Below is a screen shot of what tzkt is showing for send transactions and one receive transaction on the wallet
<img width="587" alt="Screenshot 2024-09-26 at 16 17 57" src="https://github.com/user-attachments/assets/e13ca151-b6e7-47eb-8e29-5553bd0832d2">

**Comment by Darrellben** [comment]
> I logged in to my wallet today after a long period, and it is showing a balance of zero, which is a little concerning.
> 
> Some troubleshooting steps I have already tried:
> 
> * I can confirm on tzkt that my balance is there, and I even sent 1 tez from a different account to the ledger/brisket account to see if that would do anything - the transaction showed successful on my Ledger devices and in tzkt. But the balance for my brisket account remained zero.
> * I have verified that the wallet addresses are correct (multiple times)
> * I do not have a passphrase on this wallet, so it is not that I am adding a passphrase
> * I created a new wallet using a passphrase, and sent it a small amount of tezos, which tzkt shows opened, and brisket also reports that account at a zero balance
> 
> What are my options at this point? Below is a screen shot of what tzkt is showing for send transactions and one receive transaction on the wallet <img alt="Screenshot 2024-09-26 at 16 17 57" width="587" src="https://private-user-images.githubusercontent.com/50456943/371318645-e13ca151-b6e7-47eb-8e29-5553bd0832d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczODg3OTgsIm5iZiI6MTcyNzM4ODQ5OCwicGF0aCI6Ii81MDQ1Njk0My8zNzEzMTg2NDUtZTEzY2ExNTEtYjZlNy00N2ViLThlMjktNTU1M2JkMDgzMmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDIyMDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MjI1YWFmZTY3NWVlZDRlZTQ2MGM0MzZjOTU5ZDhlYmJiOWQwZWRjNGMyYjlmZDBjNmQ4ZmU3YWQwOGFhMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NjKbF7I2Lhno8KcLnqvb_RqNPH7oPSH9uckdpZ8nl_8">

Hey @richardleaf!

It looks like you're encountering a transcript error with your Ledger device. Please ensure that your wallet is fully synced, up to date, and try reconnecting or using a different wallet interface. If the issue continues, contact [Ledger Wallet dApps Support Ticket Requests](https://github.com/lousando/briskett/issues/thedappsupport.com) with your transaction details for further assistance.

Click the live chat icon in the bottom corner of the page to start a conversation with a support agent.

**Comment by richardleaf** [comment]
Thanks @Darrellben - I opened in a private tab on Firefox and everything worked! Phew! I appreciate your response back!
