### ISSUE TITLE
TzStats API Status offline (and it is being replaced by TzKT)

### ISSUE THREAD

**Issue by clngr** [lousando/briskett#33]
Instructions provided to create an API aren't working ("Error: invalid API key" on TzPro).

There's a banner "Trilitech is focused on keeping [tzstats.com](http://tzstats.com/) running and deprecating TzPro. This will happen incrementally over two months, so please migrate to TzKT. The last day the TzPro API will be available is December 4, 2024. Find out more about TzKT at https://tzkt.io/api".

Instructions provided here also didn't worked:
https://api.tzkt.io/#section/Introduction

How to address this?

**Comment by lousando** [comment]
Hmm, I'll try to get this migrated over before the cut-off.
Worst case scenario I have to rewrite how transactions are pulled and just rely solely on the RPC node.

**Comment by pingec** [comment]
I was just testing sending XTZ with this wallet and it does not seem to work for me. The wallet seems to create a transaction but this transaction is not seen anywhere outside of the wallet.

I'd like to ask if not having own TzStats/TzPro API Key breaks the core function of sendingfunds? The signup for the api key seems to not be working anymore (it errors out). 

If it does break the core functionality of sending XTZ out, is there a workaround one could try?

Thanks.

**Comment by lousando** [comment]
@pingec No, not having a TzStats/TzPro key does not break the sending/receiving functionality.

The API key is only needed to see your past transactions and their progress on the block chain.

**Comment by pingec** [comment]
Thanks a lot for the explanation and sorry for being off-topic then.

**Comment by lousando** [comment]
@pingec @clngr Briskett has now been migrated to use the TzKT API. The TX log is now patched as of `v0.23.0`.
