### ISSUE TITLE
Briskett addresses

### ISSUE THREAD

**Issue by Tarskin** [lousando/briskett#5]
Briskett lists only 5 addresses, with the derivation paths ending on /0 through to /4. However, as many users will be migrating here from SimpleStaking there is a need to be able to access the same addresses that could be accessed through there. They also added the /0/0 and /0/1 paths (for address 6 and 7). Therefore, it would be a nice feature to add this to Briskett (or the option to enter a path manually?).

Alternatively, instead of selecting the addresses before the entire process, how about showing the addresses, with balance after retrieving the public keys from the trezor and allowing the user to select the address from the shown list?

**Comment by lousando** [comment]
Wouldn't be too difficult to add the other addresses SimpleStaking supports.

To pull all addresses from the Trezor would be a bit more re-work, but it's do-able. The UI would just need to be tweaked a bit to have some sort of address switcher.

**Comment by Tarskin** [comment]
Any objection if I draft a PR for this?

**Comment by lousando** [comment]
No, no objections. Any help is appreciated :)

**Comment by lousando** [comment]
Missing Briskett addresses 6 & & added with #6

Closing this and will add create a new ticket for the dynamic address changing.
