### ISSUE TITLE
Briskett.app website wont work sometimes - nodes offline

### ISSUE THREAD

**Issue by songproducer** [lousando/briskett#8]
ECAD Labs Node Status:  OFFLINE
TzStats API Status:  OFFLINE

**Comment by lousando** [comment]
Hmm, what I can do is allow the option for multiple nodes in case one happens to be offline.

**Comment by Fleischmuck** [comment]
Hi, i can´t connect my Trezor, the Bridge is spinning forever, anyone has the same issue?

**Comment by lousando** [comment]
Hey @Fleischmuck, what browser, machine, and Trezor model are you using?

**Comment by Fleischmuck** [comment]
Hi, newest Firefox 119, Mac Ventura, Trezor Model T Latest Firmware, Latest Bridge, the bridge is working fine on other applications for me

**Comment by clngr** [comment]
Not working anymore here too, even opened a specific issue for it.

**Comment by lousando** [comment]
@Fleischmuck it seems this issue is related to Briskett not using an updated Trezor Bridge package. This is related to #19

**Comment by lousando** [comment]
@Fleischmuck Please retest Briskett at your nearest convenience to see if your issue is resolved as I think this was related to #19 and I believe that issue to be fixed now.

**Comment by Fleischmuck** [comment]
@lousando resolved! many thx !! Is there a way to acces KT adresses ?

**Comment by lousando** [comment]
@Fleischmuck There currently isn't. However, #22 has been opened recently. 
I think this will be the next feature on the roadmap.

**Comment by Fleischmuck** [comment]
Would be great, theres no wallet with access to KT adresses out there -.-
